export const ROUTES = {
  ABOUTUS: { label: "About Us", path: "/about" },
  ADD_TO_CART: { label: "Add to Cart", path: "/addtocart" },
  ADMIN: { label: "Admin", path: "/admin" },
  ARTWORK: { label: "Artwork", path: "/artwork" },
  CONTACTUS: { label: "Contact Us", path: "/contact" },
  CREATEITEM: { label: "Create Item", path: "/create" },
  CART: { label: "Cart", path: "/cart" },
  DISCOVER: { label: "Discover", path: "/discover" },
  HOME: { label: "Home", path: "/" },
  HOTBID: { label: "Hot Bid", path: "/hotbid" },
  LOGIN: { label: "Login", path: "/login" },
  LOGOUT: { label: "Logout", path: "/logout" },
  ORDER: { label: "Order", path: "/order" },
  PROFILE: { label: "Profile", path: "/profile" },
  SIGNUP: { label: "Signup", path: "/signup" },
  CATEGORIES: { label: "Categories", path: "/categories" },
};
