#!/usr/bin/env sh

# Stop the process and return false to
ctrl_c() {
  echo Stoping checks...
  false
}

# ctrl_c is the name of the signal ctrl_c function for SIGINT signal
trap 'ctrl_c' SIGINT

sh ./.hooks/prepare.sh

# Perform distribution, testing and docs creation only if the 'src' folder contents are modified.
IS_SRC_MODIFIED=$(git status -s src)

if [ ! -z "$IS_SRC_MODIFIED" -a "$IS_SRC_MODIFIED" != " " ]; then
  echo
  echo "Build checks... 🛠️"
  pnpm build
  echo
  # echo "Types checks... 🩺"
  # pnpm typecheck
  ERR=$?

  if [ $ERR -eq 0 ]; then
    echo "Checking all staged files."
  else
    echo "Build Failed."
    echo "Fix type issues, add changes and try commit again."
    exit 1
  fi

  echo
  echo "Lint checks... 📃"
  pnpm lint-staged
  ERR=$?

  if [ $ERR -eq 0 ]; then
    echo "Formated all staged files."
  else
    echo "code formatting check Failed."
    echo "Run 'pnpm lint-staged', add changes and try commit again."
    exit 1
  fi
fi

# Get the list of modified files and save to a temporary file
MODIFIED_FILES=$(git diff --cached --name-only)
echo "$MODIFIED_FILES" >.git/MODIFIED_FILES.tmp
